version: '3.8'

services:
  spring_boot:
    build: ./spring-docker
    container_name: spring_boot
    depends_on:
      - mysql
    environment:
      SPRING_SERVER_PORT: 8001
      SPRING_DATABASE_PORT: 3306
      SPRING_DATABASE_NAME: docker_db
      SPRING_DATABASE_ADDRESS: mysql
    ports:
      - '8000:8001'
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - mysql-1:/var/lib/mysql
      - ./mysql-docker/Books.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    depends_on:
      - mysql
    restart: always
    ports:
      - '3100:8080'

volumes:
  mysql-1:
    driver: local