version: '3.8'

services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3000:3306'
    volumes:
      - mysql-1:/var/lib/mysql
      - ./mysql-docker/Books.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    depends_on:
      - mysql
    restart: always
    ports:
      - '3100:8080'

volumes:
  mysql-1:
    driver: local